FROM bitnami/spark:3.5.5-debian-12-r3

USER 0

COPY spark_kafka_hdfs.py /spark_kafka_hdfs.py
COPY scripts/spark_startup.sh /spark_startup.sh

RUN apt update && apt install -y python-is-python3 python3-pip && ln -sf /usr/bin/pip3 /usr/bin/pip && pip install pyspark kafka-python hdfs

RUN chmod +x /spark_startup.sh
CMD ["/bin/bash", "/spark_startup.sh"]