# Dockerfile.search
FROM python:3.8-slim

# Cài đặt các gói cần thiết: torch, transformers, torchvision và pillow
RUN pip install torch transformers torchvision pillow

# Copy các file search vào container
COPY t5_image_search.py /app/t5_image_search.py
COPY resnet_image_search.py /app/resnet_image_search.py

WORKDIR /app

# Mặc định chạy t5_image_search.py, có thể override CMD khi cần chạy resnet_image_search.py
CMD ["python", "t5_image_search.py"]

