FROM bitnami/kafka:3.9.0-debian-12-r12

USER 0

COPY kafka_producer.py /kafka_producer.py
COPY scripts/kafka_startup.sh /kafka_startup.sh
COPY requirements.txt /requirements.txt

RUN apt update && apt install -y python-is-python3 python3-pip && pip install pyspark kafka-python hdfs --break-system-packages
RUN pip install -r /requirements.txt --break-system-packages

# create kafka topic upon container startup
RUN  chmod +x /kafka_startup.sh