version: '3'

services:
  namenode:
    image: apache/hadoop:3.3.5
    container_name: namenode
    hostname: namenode
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./hadoop_namenode:/opt/hadoop/data/nameNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./start-hdfs.sh:/start-hdfs.sh
      - ./flickr30k_images:/data/images
      - ./results.csv:/data/results.csv
    ports:
      - "9870:9870"
    command: [ "/bin/bash", "/start-hdfs.sh" ]
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.2

  datanode1:
    image: apache/hadoop:3.3.5
    container_name: datanode1
    hostname: datanode1
    user: root
    environment:
      - HADOOP_HOME=/opt/hadoop
    volumes:
      - ./hadoop_datanode1:/opt/hadoop/data/dataNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    depends_on:
      - namenode
    command: [ "/bin/bash", "/init-datanode.sh" ]
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.3

  kafka:
    image: bitnami/kafka:3.9.0-debian-12-r12
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.6

  t5-search:
    build:
      context: .
    container_name: t5-search
    depends_on:
      - spark-master
    volumes:
      - ./results.csv:/data/results.csv
    env_file:
      - .env
    command: [ "/entrypoint.sh" ]
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.9
    environment:
      - KAFKA_SERVER=kafka:9092  # Đảm bảo t5-search có thể kết nối đến Kafka
      - KAFKA_IMAGE_TOPIC=image_topic
      - KAFKA_CAPTION_TOPIC=caption_topic
    # Thêm bất kỳ biến môi trường nào cần thiết cho t5-search

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.7

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      hdfs_network:
        ipv4_address: 172.20.0.8

networks:
  hdfs_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16







